### ISSUE TITLE
안녕하세요 조드래곤나인님, 블로그에 자그마한 요청 사항이 있습니다만.

### ISSUE THREAD

**Issue by LumiLoves** [ChoDragon9/ChoDragon9.github.io#8]
안녕하세요. 조드래곤나인님 :)

블로그를 자주 들락날락 거리며 많은 도움을 얻고 있는 방문자입니당 🙂

항상 양질의 글 올려주셔서 감사히 보고 있습니다 *^0^*

다름이 아니라, 블로그 디자인이 리뉴얼 되면서 갑작스럽게 문의드리고 싶은 사항이 있어 이슈를 쓰게 되었습니다

오늘 두가지 글을 한꺼번에 열어서 보는데, 
그만 아래 화면 처럼 어느 화면에 무슨 글을(?) 열어놨는지 알지 못하는 사태가 발생하고 말았습니다...
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/23192677/83256269-1c292100-a1ed-11ea-8a43-d69fd9bca9e8.png">

저는 주소창에 적힌 영어를 통해서만 글의 제목을 추측할 수가 있었던 것이죠..

바쁘시겠지만, 글을 열면 기존 디자인처럼 제목이 보일 수 있게 개선이 가능할까욤?

제 요청사항을 들어주신다면, 지금 하시는 프로젝트의 동료분들께 커피도 얻고, 프로젝트가 잘 릴리즈 될 것 같네요 :)

긴 글 읽어주셔서 감사합니다~

**Comment by ChoDragon9** [comment]
@LumiLoves 안녕하세요 :) 공대아름님
좋은 관심과 의견을 주셔서 감사합니다.

확실히 현재 어떤 글을 보고 있는 지 어려움이 있어 보입니다.
이 부분은 바로 개선하도록 하겠습니다 👍

**Comment by ChoDragon9** [comment]
@LumiLoves
일단 모든 페이지에 **왼쪽 사이드 메뉴** 노출하는 형태로 변경했습니다 :)

<img width="1679" alt="스크린샷 2020-05-29 오후 10 14 13" src="https://user-images.githubusercontent.com/17817719/83263625-e0488880-a1f9-11ea-8ebd-334d5c74788e.png">

사이드 메뉴에 목차들이 노출되는 것은 점진적으로 변경될 예정입니당
의견 감사합니다 (_ _)

**Comment by LumiLoves** [comment]
@ChoDragon9 
우왓👻 이렇게 초스피드로 반영해주셔서
넘나 감사합니당! 짱짱!

**Comment by ChoDragon9** [comment]
@LumiLoves 감사합니다 :)
추가적으로, 모바일로 봤을 때 제목이 안보여
이전 블로그 형태 처럼 제목이 보이도록 수정했습니다.

<img width="1678" alt="스크린샷 2020-05-29 오후 11 06 27" src="https://user-images.githubusercontent.com/17817719/83268877-353bcd00-a201-11ea-8907-d184893445f8.png">

좋은 의견 감사합니당 👍
